[package]
name = "sourcesecrets"
version = "0.1.0"
authors = ["Lander Brandt <labrandt@microsoft.com>"]

[dependencies]
csv = "1.0.0-beta.5"
clap = "2.29"
regex = "1"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
pbr = "1.0"
base64 = "0.9"
scopeguard = "0.3"
